[package]

name = "core"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]

[lib]
name = "core"
doctest = false

[target.arm-linux-androideabi.dependencies]
android_glue = "*"

[dependencies]
cgmath = "*"
rand = "*"
num = "*"
